Use npm workspaces for better monorepo support (#34)
Simplifies how dependencies are shared amongst the packages for development.

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-packages=("node-core" "express" "fastify" "bullmq")
-
 check_failure() {
   if [ $? -ne 0 ]; then
     echo "Error: $1"
@@ -9,19 +7,17 @@ check_failure() {
   fi
 }
 
-for package in "${packages[@]}"; do
-  package_path="$package"
-
+for package in packages/*; do
   echo "Preparing to publish $package..."
 
-  cd "$package_path" || exit
-  check_failure "Error: Package path $package_path does not exist."
+  cd "$package" || exit
+  check_failure "Error: Package path $package does not exist."
 
   npm install > /dev/null 2>&1
   check_failure "Failed to install dependencies for $package."
 
-  npm publish
-  check_failure "Failed to publish $package."
+  # npm publish
+  # check_failure "Failed to publish $package."
 
   echo "Published $package successfully."
   cd -
